version: 0.0
os: linux

# 배포할 파일 및 디렉토리 정의
files:
  - source: /
    destination: /home/ubuntu/streaming

# 애플리케이션 소유 원한 정의
permissions:
  - object: /home/ubuntu/steaming/
    owner: ubuntu
    group: ubuntu

# 배포 단계에 실행할 hook 정의
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu
