# This file is used when the S3 profile is active
spring:
  config:
    activate:
      on-profile: "aws"
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB

cloud:
  aws:
    stack:
      auto: false
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_S3_BUCKET}
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error