server:
  port: ${APPLICATION_PORT:8080}

spring:
  application:
    name: Streaming Service
  profiles:
    group:
      "local": "local, datasource, docs, aws" # 로컬 환경 프로파일
      "dev": "dev, datasource, docs, aws" # 개발 환경 프로파일

    active: dev # 로컬 환경 프로파일을 기본으로 설정
