name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    name: CI

    # 해당 jobs에서 아래의 step들이 어떤 환경에서 실행 될 것인지 설정
    runs-on: ubuntu-latest

    steps:
      # 작업에서 액세스 할 수 있도록 $GITHUB_WORKSPACE에서 저장소 체크아웃
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'

      # gradlew 작업에 대한 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      # Build 실행
      - name: Build with Gradle
        run: ./gradlew build
        shell: bash
